name: clarity
description: Clarity — ежедневный анализ речи
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Fonts & UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # Charts
  fl_chart: ^0.66.2

  # Storage
  shared_preferences: ^2.2.3

  # Networking
  http: ^1.2.2
  path_provider: ^2.1.4

  # Audio
  record: ^5.1.2
  audioplayers: ^6.0.0

  # Misc
  file_picker: ^8.0.0

dependency_overrides:
  record_linux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
